name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=23.3.2
  - scikit-learn=1.3.2
  - matplotlib==3.7.3
  - plotly==5.18.0
  - pillow=10.2.0
  - mlflow=2.10.0
  - pip:
      - wandb==0.16.2
      - omegaconf==2.3.0